config/routes.rb
Rails.application.routes.draw do
  root 'samples#index'

  resources :principal_investigators

  resources :projects

  resources :samples do
    collection { post :import }
  end
end

app/models/principal_investigator.rb
class PrincipalInvestigator < ActiveRecord::Base
  has_many :projects
  has_many :samples, :through => :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :principal_investigator
  has_many :samples
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :project
  delegate :principal_investigator, :to => :project, :allow_nil => true

  scope :order_by_principal_investigator, -> { joins(:project => :principal_investigator).order('last_name') }
  scope :order_by_project_number, -> { joins(:project).order('number') }

  def self.import file
    # ensure file is readable
    file.rewind

    CSV.foreach(file.path, { :headers => true, :col_sep => "\t"  }) do |row|

      # create principal investor from hash of attributes
      principal_investor = PrincipalInvestigator.find_or_create_by(principal_investor_attributes(row[0]))

      # create project from hash of attributes
      project = Project.find_or_create_by(project_attributes(row[1]))

      # associate project with principal investor
      principal_investor.projects << project

      # create sample from hash of attributes
      sample = Sample.find_or_create_by(sample_attributes(row))

      # associate sample with project
      project.samples << sample
    end
  end

  def self.principal_investor_attributes full_name
    first_name = full_name.split(" ").first
    last_name = full_name.split(" ").last
    { "first_name" => first_name, "last_name" => last_name }
  end

  def self.project_attributes number
    { "number" => number }
  end

  def self.sample_attributes row
    identifier = row[2]
    total_reads = row[3]
    average_q_score = row[4]
    percent_five_x_coverage = row[5]
    percent_ten_x_coverage = row[6]
    percent_twenty_x_coverage = row[7]
    percent_thirty_x_coverage = row[8]
    { "identifier" => identifier, "total_reads" => total_reads, "average_q_score" => average_q_score, "percent_five_x_coverage" => percent_five_x_coverage, "percent_ten_x_coverage" => percent_ten_x_coverage, "percent_twenty_x_coverage" => percent_twenty_x_coverage, "percent_thirty_x_coverage" => percent_thirty_x_coverage }
  end

  def self.passable
    where('percent_five_x_coverage > 98')
    .where('percent_ten_x_coverage > 90')
    .where('percent_twenty_x_coverage > 75')
    .where('percent_thirty_x_coverage > 65').order(:id)
  end

  def self.unpassable
    passable_sample_ids = Sample.passable.pluck(:id)
    Sample.where.not(:id => passable_sample_ids)
  end

  def passable?
    Sample.passable.pluck(:id).include?(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/principal_investigators_controller.rb
class PrincipalInvestigatorsController < ApplicationController
  def show
    @principal_investigator = PrincipalInvestigator.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @project_samples = @project.samples.order(:created_at)
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index
    case params[:sort]
    when "principal_investigator"
      @samples = Sample.order_by_principal_investigator
    when "project_number"
      @samples = Sample.order_by_project_number
    when "passable"
      @samples = Sample.passable
    when "unpassable"
      @samples = Sample.unpassable
    else
      @samples = Sample.order(sort_column)
    end
  end

  def import
    if params[:file].blank?
      redirect_to root_url, :notice => "Please add a file to upload."
    else
      Sample.import(params[:file])
      redirect_to root_url, :notice => "Samples imported!"
    end
  end

  private
    def sort_column
      sample_columns = %w[identifier total_reads average_q_score percent_five_x_coverage percent_ten_x_coverage percent_twenty_x_coverage percent_thirty_x_coverage]
      sample_columns.include?(params[:sort]) ? params[:sort] : "created_at"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title QcMetrics
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if notice
      .messages
        .col-md-12.col-sm-12.col-xs.12
          %p.notice
            = notice

    - if alert
      .messages
        .col-md-12.col-sm-12.col-xs.12
          %p.alert
            = alert

    = yield

app/views/principal_investigators/show.html.haml
.col-md-12.col.sm-12.col-xs-12
  #pi_title_section
    %h1= "#{@principal_investigator.first_name} #{@principal_investigator.last_name}"

  #project_list
    - @principal_investigator.projects.each do |project|
      %h2= link_to "Project Number: #{project.number}", project_path(project.id)

  .root_link
    = link_to "Back to Index", root_url

app/views/projects/show.html.haml
.col-md-12.col-sm-12.col-xs-12
  #project_title_section
    %h1= "Project Number: #{@project.number}"
    %h1
      Principal Investigator:
      = link_to "#{@project.principal_investigator.first_name} #{@project.principal_investigator.last_name}", principal_investigator_path(@project.principal_investigator.id)

  #project_table
    %table
      %tr
        %th Identifier
        %th Total Reads
        %th Average Q Score
        %th Percent 5x Coverage
        %th Percent 10x Coverage
        %th Percent 20x Coverage
        %th Percent 30x Coverage

      - @project_samples.each do |sample|
        %tr
          %td= sample.identifier
          %td= sample.total_reads
          %td= sample.average_q_score
          %td= sample.percent_five_x_coverage
          %td= sample.percent_ten_x_coverage
          %td= sample.percent_twenty_x_coverage
          %td= sample.percent_thirty_x_coverage

  .root_link
    = link_to "Back to Index", root_url

app/views/samples/index.html.haml
.col-md-4.col-sm-12.col-xs-12
  .title_section
    %h1 VANTAGE SAMPLES

.col-md-4.col-sm-12.col-xs-12
  #filter_section
    Filter by:
    = link_to "PASSABLE", :sort => "passable"
    = link_to "UNPASSABLE", :sort => "unpassable"
    = link_to "ALL", :sort => "all"

.col-md-4.col-sm-12.col-xs-12
  #import_form
    = form_tag import_samples_path, :multipart => true do
      = file_field_tag :file
      = submit_tag "IMPORT"

.col-md-12.col-sm-12.col-xs-12
  %table
    %tr
      %th= link_to "Principal Investigator", :sort => "principal_investigator"
      %th= link_to "Project Number", :sort => "project_number"
      %th= link_to "Identifier", :sort => "created_at"
      %th= link_to "Total Reads", :sort => "total_reads"
      %th= link_to "Average Q Score", :sort => "average_q_score"
      %th= link_to "Percent 5x Coverage", :sort => "percent_five_x_coverage"
      %th= link_to "Percent 10x Coverage", :sort => "percent_ten_x_coverage"
      %th= link_to "Percent 20x Coverage", :sort => "percent_twenty_x_coverage"
      %th= link_to "Percent 30x Coverage", :sort => "percent_thirty_x_coverage"
      %th= "PASSABLE?"

    - @samples.each do |sample|
      %tr
        %td= link_to "#{sample.principal_investigator.first_name} #{sample.principal_investigator.last_name}", principal_investigator_path(sample.principal_investigator.id)
        %td= link_to sample.project.number, project_path(sample.project.id)
        %td= sample.identifier
        %td= sample.total_reads
        %td= sample.average_q_score
        %td= sample.percent_five_x_coverage
        %td= sample.percent_ten_x_coverage
        %td= sample.percent_twenty_x_coverage
        %td= sample.percent_thirty_x_coverage
        %td= sample.passable? ? "Yes" : "No"